name: category_question_link
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: http://ondart.me/
version: 0.0.9
description: >
  dartling is a domain model framework.
  A new dartling project is copied and adapted from dartling_skeleton.
dependencies:
  dartling:
    git: git://github.com/dzenanr/dartling.git